language: generic
addons:
  ssh_known_hosts: 125.212.227.42
install: cd /home/hoangnm/web/ai-news.xyz/html && git pull origin master
before_install:
- openssl aes-256-cbc -K $encrypted_0ab9dbbafe5f_key -iv $encrypted_0ab9dbbafe5f_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
